# Generated by Django 4.1.7 on 2023-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctorid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
