# Generated by Django 4.1.7 on 2023-02-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_alter_reservation_doctorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='doctorid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
