# Generated by Django 4.1.7 on 2023-02-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_delete_doctor_alter_reservation_doctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='doctorid',
        ),
    ]
