# Generated by Django 4.1.7 on 2023-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_remove_reservation_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='doctorid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
